# Generated by Django 3.2.9 on 2021-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='description',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='addpost',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
