# Generated by Django 3.2.9 on 2021-11-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20211105_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
