# Generated by Django 3.2.9 on 2021-11-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_addpost_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='image',
        ),
        migrations.AddField(
            model_name='addpost',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
